import { h, toast } from '../ui.js';
import { buildBPE, tokenize, tokenStats } from '../tokenizer.js';

export function renderTokenizerLab(state, onUpdate) {
  const container = h('div');

  const hero = h('div', { class: 'card hero' },
    h('span', { class: 'chip acc', text: 'Subword Tokenization' }),
    h('h2', { text: 'Byte-Pair Encoding (BPE) Lab' }),
    h('p', { text: 'Large language models do not see words or letters. They see numeric tokens generated by Byte-Pair Encoding. Watch characters merge into subwords step-by-step.' }),
  );
  container.append(hero);

  const card = h('div', { class: 'card' });
  card.append(
    h('h3', { text: 'Live Tokenizer Workbench' }),
    h('p', { text: 'Type any text (Hindi, English, code, or mixed) and watch the tokenizer segment it into token tokens:' })
  );

  const defaultSample = 'Transformers learn language by predicting the next subword token through self-attention layers.';

  const inputArea = h('textarea', {
    placeholder: 'Enter text to tokenize...',
    value: defaultSample,
    style: { minHeight: '90px' }
  });
  card.append(inputArea);

  // Compression & Vocab Stats
  const statsBox = h('div', { class: 'grid2', style: { marginTop: '12px', marginBottom: '12px' } },
    h('div', { class: 'stat' },
      h('div', { class: 'v', id: 'tok-count', text: '—' }),
      h('div', { class: 'k', text: 'Total Tokens' })
    ),
    h('div', { class: 'stat' },
      h('div', { class: 'v', id: 'tok-ratio', text: '—' }),
      h('div', { class: 'k', text: 'Characters / Token' })
    )
  );
  card.append(statsBox);

  // Visual Token Stream
  card.append(
    h('h4', { style: { margin: '14px 0 8px', fontSize: '13.5px' }, text: 'Visual Token Stream (Color Segmented)' })
  );

  const streamBox = h('div', {
    class: 'tok-stream',
    style: {
      minHeight: '70px',
      padding: '12px',
      background: 'rgba(5, 8, 15, 0.9)',
      border: '1px solid var(--border)',
      borderRadius: '12px'
    }
  });
  card.append(streamBox);

  // BPE Merge Rules Inspector
  const mergeSection = h('div', { style: { marginTop: '16px' } },
    h('h4', { style: { margin: '0 0 6px', fontSize: '13.5px' }, text: 'Discovered BPE Merges (Top Frequent Pairs)' }),
    h('div', { id: 'merge-rules-list', style: { display: 'flex', flexWrap: 'wrap', gap: '6px' } })
  );
  card.append(mergeSection);

  function updateTokens() {
    const text = inputArea.value || '';
    if (!text.trim()) {
      streamBox.innerHTML = '<span style="color:var(--muted);font-size:12px;">Type above to visualize tokens...</span>';
      card.querySelector('#tok-count').textContent = '0';
      card.querySelector('#tok-ratio').textContent = '0.0';
      return;
    }

    // Build BPE model on current input text
    const { codebook } = buildBPE(text, 24);
    const { perWord, tokens, chars, ratio } = tokenStats(text, codebook);

    card.querySelector('#tok-count').textContent = String(tokens);
    card.querySelector('#tok-ratio').textContent = ratio.toFixed(2);

    // Render tokens in stream
    streamBox.innerHTML = '';
    const colors = [
      'rgba(109, 141, 255, 0.16)',
      'rgba(67, 224, 212, 0.16)',
      'rgba(255, 180, 84, 0.16)',
      'rgba(61, 220, 151, 0.16)',
      'rgba(255, 107, 129, 0.16)',
    ];

    let colorIdx = 0;
    perWord.forEach((w) => {
      w.tokens.forEach((t) => {
        const bg = colors[colorIdx % colors.length];
        colorIdx++;
        const tokEl = h('span', {
          class: 'tok',
          style: { background: bg },
          text: t
        });
        streamBox.append(tokEl);
      });
      // Space separator
      const spaceEl = h('span', { class: 'tok sp', text: '␣' });
      streamBox.append(spaceEl);
    });

    // Render BPE merge rules
    const mergeRulesContainer = card.querySelector('#merge-rules-list');
    mergeRulesContainer.innerHTML = '';
    if (codebook.length === 0) {
      mergeRulesContainer.innerHTML = '<span style="color:var(--muted);font-size:12px;">Type more repetitive phrases to see BPE pair mergers.</span>';
    } else {
      codebook.slice(0, 12).forEach((rule, idx) => {
        const chip = h('span', {
          class: 'chip warn',
          style: { fontSize: '11px' },
          text: `#${idx + 1}: "${rule.a}" + "${rule.b}" → "${rule.merged}" (${rule.count}x)`
        });
        mergeRulesContainer.append(chip);
      });
    }
  }

  inputArea.addEventListener('input', updateTokens);
  setTimeout(updateTokens, 30);

  container.append(card);
  return container;
}
